repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.11
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  # Monorepo: ensure backend/uv.lock stays up to date
  - repo: local
    hooks:
      - id: uv-backend-lock
        name: uv lock (backend)
        language: system
        entry: bash
        args: ["-lc", "cd backend && uv lock"]
  
  # JavaScript/TypeScript linting and formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|md)$
        exclude: ^(dist|build)/
  
  # ESLint (currently disabled due to TypeScript plugin dependency)
  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: ESLint
  #       entry: npx eslint
  #       language: system
  #       files: \.(js|jsx|ts|tsx)$
  #       exclude: ^(dist|build)/
  #       pass_filenames: true
