services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    working_dir: /app/backend
    volumes:
      - .:/app
      # Use anonymous volumes to avoid sharing host's .venv
      # Renew volumes when you change packages with
      # `docker compose up --renew-anon-volumes`
      - /app/.venv
    ports:
      - "8000:8000"
    command: >
      uv run uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    image: oven/bun:1
    working_dir: /app/frontend
    restart: unless-stopped
    environment:
      # When running both services in containers, proxy to backend service name
      VITE_BACKEND_ORIGIN: http://app:8000
      NODE_ENV: development
    volumes:
      - .:/app
      # Use anonymous volume for node_modules inside container
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    command: >
      bash -lc "bun install && bun run dev --host 0.0.0.0"
    depends_on:
      - app
