services:
  marimo:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    working_dir: /app/apps/backend
    environment:
      API_BASE_URL: http://app:8000
      USER_ID: ${USER_ID:-1000}
      GROUP_ID: ${GROUP_ID:-1000}
      USER_NAME: ${USER_NAME:-developer}
      GROUP_NAME: ${USER_NAME:-developer}
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "2718:2718"
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: >-
      bash -lc "set -o pipefail; mkdir -p /app/.logs && uv run --no-sync marimo run extensions/marimo/app.py --host 0.0.0.0 --port 2718 2>&1 | tee -a /app/.logs/marimo.log"
    depends_on:
      - app

  proxy:
    depends_on:
      - frontend
      - app
      - workspace
      - marimo

  dev:
    ports:
      - "2718:2718"
